- name: "copy orderer artifacts"
  synchronize:
    src: "/home/{{ fabric.user }}/build/fabric/org{{ org_id }}/pkg-orderer{{ org_id }}"
    dest: "/home/{{ fabric.user }}"
  delegate_to: "{{ groups['build'][0] }}"
 
- name: "add orderer systemd service file"
  remote_user: root
  template:
    src: "../files/orderer.service"
    dest: "/etc/systemd/system/orderer.service"
    mode: 0644

