---
- hosts: localhost
  gather_facts: False
  vars_files:
  - "{{ lookup('env','VARS_FILE') }}"
  tasks:
  - name: Gather EC2 facts
    ec2_instance_facts:
      filters:
        "tag:Class": fabric
        instance-state-name: running
    register: facts

  - debug: var=facts

  - ec2:
      state: absent
      region: "{{ region }}"
      instance_ids: "{{ item.instance_id }}"
    with_items: "{{ facts.instances }}"
